const usersData = [
  {id: 0, url: 'www.agetic.gob.bo', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 1, url: 'adsib.gob.bo', registered: '2018/01/01', role: 'Member', status: 'Active'},
  {id: 2, url: 'att.gob.bo', registered: '2018/02/01', role: 'Staff', status: 'Banned'},
  {id: 3, url: 'bolivia.gob.bo', registered: '2018/02/01', role: 'Admin', status: 'Inactive'},
  {id: 4, url: 'fbm.gob.bo', registered: '2018/03/01', role: 'Member', status: 'Pending'},
  {id: 5, url: 'www.abt.gob.bo', registered: '2018/01/21', role: 'Staff', status: 'Active'},
  {id: 6, url: 'www.academiadiplomatica.gob.bo', registered: '2018/01/01', role: 'Member', status: 'Active'},
  {id: 7, url: 'www.aduana.gob.bo', registered: '2018/02/01', role: 'Staff', status: 'Banned'},
  {id: 8, url: 'www.abc.gob.bo', registered: '2018/02/01', role: 'Admin', status: 'Inactive'},
  {id: 9, url: 'www.aben.gob.bo', registered: '2018/03/01', role: 'Member', status: 'Pending'},
  {id: 10, url: 'www.aduana.gob.bo', registered: '2018/01/21', role: 'Staff', status: 'Active'},
  {id: 11, url: 'Carwyn Fachtna', registered: '2018/01/01', role: 'Member', status: 'Active'},
  {id: 12, url: 'Nehemiah Tatius', registered: '2018/02/01', role: 'Staff', status: 'Banned'},
  {id: 13, url: 'Ebbe Gemariah', registered: '2018/02/01', role: 'Admin', status: 'Inactive'},
  {id: 14, url: 'Eustorgios Amulius', registered: '2018/03/01', role: 'Member', status: 'Pending'},
  {id: 15, url: 'Leopold Gáspár', registered: '2018/01/21', role: 'Staff', status: 'Active'},
  {id: 16, url: 'Pompeius René', registered: '2018/01/01', role: 'Member', status: 'Active'},
  {id: 17, url: 'Paĉjo Jadon', registered: '2018/02/01', role: 'Staff', status: 'Banned'},
  {id: 18, url: 'Micheal Mercurius', registered: '2018/02/01', role: 'Admin', status: 'Inactive'},
  {id: 19, url: 'Ganesha Dubhghall', registered: '2018/03/01', role: 'Member', status: 'Pending'},
  {id: 20, url: 'Hiroto Šimun', registered: '2018/01/21', role: 'Staff', status: 'Active'},
  {id: 21, url: 'Vishnu Serghei', registered: '2018/01/01', role: 'Member', status: 'Active'},
  {id: 22, url: 'Zbyněk Phoibos', registered: '2018/02/01', role: 'Staff', status: 'Banned'},
  {id: 23, url: 'Einar Randall', registered: '2018/02/01', role: 'Admin', status: 'Inactive'},
  {id: 24, url: 'Félix Troels', registered: '2018/03/21', role: 'Staff', status: 'Active'},
  {id: 25, url: 'Aulus Agmundr', registered: '2018/01/01', role: 'Member', status: 'Pending'},
  {id: 42, url: 'Ford Prefex', registered: '2001/05/21', role: 'Alien', status: 'Don\'t panic!'}
]

export default usersData
